apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongocredentials
              key: ME_CONFIG_MONGODB_ADMINUSERNAME

        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongocredentials
              key: ME_CONFIG_MONGODB_ADMINPASSWORD

        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodata
          mountPath: /data
      volumes:
      - name: mongodata
        persistentVolumeClaim:
          claimName: mongo-persistent-volume-claim


---
apiVersion: v1
kind: Service
metadata:
  name: mongoservice
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mongo-storage-class
  hostPath:
    path: /home/sakthi/kubestorage/mongo


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume-claim
spec:
  storageClassName: mongo-storage-class
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany


---
apiVersion: v1
kind: Secret
metadata:
  name: mongocredentials
type: Opaque
stringData:
  ME_CONFIG_MONGODB_ADMINUSERNAME: sakthisaran
  ME_CONFIG_MONGODB_ADMINPASSWORD: mongoSecret001BySakthi


